version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: talentu
    container_name: talentu-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - talentu
  
  db:
    image: mysql:5.7
    container_name: talentu-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: dbbolsaempleo
      MYSQL_ROOT_PASSWORD: admin.root
      MYSQL_PASSWORD: password
      MYSQL_USER: dbbolsaempleo
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - 33060:3306
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - talentu

  nginx:
    image: nginx:1.17-alpine
    container_name: talentu-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - talentu

networks:
  talentu:
    driver: bridge
